[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.version]
path = "bumpversion/__init__.py"

[project]
name = "bumpversion2"
description = "Make it easy to bump version by command line."
authors = [{name="Waket Zheng", email="waketzheng@gmail.com"}]
license = {text="MIT"}
readme = "README.md"
keywords = ["bumpversion"]
requires-python = ">=3.10"
dynamic = [ "version" ]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[dependency-groups]
dev = [
    "mypy >=1.18.2",
    "pytest >=8.4.2",
    "testfixtures >=8.3.0",
]

[project.scripts]
bumpversion = "bumpversion:cli.main"

[tool.ruff.lint]
extend-select = [
    "I",      # https://docs.astral.sh/ruff/rules/#isort-i
    "SIM",    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "FA",     # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
    "UP",     # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "RUF100", # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]
ignore = ["UP031"] # https://docs.astral.sh/ruff/rules/printf-string-formatting/

[tool.mypy]
pretty = true
python_version = "3.10"
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["tests.test_functions"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.test_version_part"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.test_cli"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "testfixtures.*",
]
ignore_missing_imports = true
